/* Generated by Nim Compiler v2.0.8 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_GLerror__pecJ3qrtkP9cNFDFcCVFvuA tyObject_GLerror__pecJ3qrtkP9cNFDFcCVFvuA;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__LaG9a3ln9cHpAtM2PoiEBtMA tySequence__LaG9a3ln9cHpAtM2PoiEBtMA;
typedef struct tySequence__LaG9a3ln9cHpAtM2PoiEBtMA_Content tySequence__LaG9a3ln9cHpAtM2PoiEBtMA_Content;
typedef struct tyObject_RefHeader__m5DjWPRDLSOOpTFPKmlVBA tyObject_RefHeader__m5DjWPRDLSOOpTFPKmlVBA;
typedef struct tyObject_GcEnv__YZbBpAB7y9bEm9a6qzlH6rdw tyObject_GcEnv__YZbBpAB7y9bEm9a6qzlH6rdw;
typedef struct tyObject_CellSeq__NbFHq68WBMdljkCuuVfjIw tyObject_CellSeq__NbFHq68WBMdljkCuuVfjIw;
typedef struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q tyTuple__N4J9cV4JZGem3ljqqj5rT0Q;
typedef struct tyObject_CellSeq__MZ3vrnJoRJ9cOe8aQ89bLCEQ tyObject_CellSeq__MZ3vrnJoRJ9cOe8aQ89bLCEQ;
typedef struct tyTuple__v8m6PEFL3KMh2a55VJabyg tyTuple__v8m6PEFL3KMh2a55VJabyg;
typedef struct tyObject_StackTraceEntry__AolQsxmhMZzaZBPezNXohw tyObject_StackTraceEntry__AolQsxmhMZzaZBPezNXohw;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NI32 tyEnum_GLerrorCode__9aa0fSh3zKRU4fPbvvwy9bOg;
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	NCSTRING name;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
};
struct RootObj {
TNimTypeV2* m_type;
};
struct tySequence__LaG9a3ln9cHpAtM2PoiEBtMA {
  NI len; tySequence__LaG9a3ln9cHpAtM2PoiEBtMA_Content* p;
};
struct Exception {
  RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__LaG9a3ln9cHpAtM2PoiEBtMA trace;
	Exception* up;
};
struct tyObject_GLerror__pecJ3qrtkP9cNFDFcCVFvuA {
  Exception Sup;
	tyEnum_GLerrorCode__9aa0fSh3zKRU4fPbvvwy9bOg code;
};
struct tyObject_RefHeader__m5DjWPRDLSOOpTFPKmlVBA {
	NI rc;
	NI rootIdx;
};
struct tyObject_CellSeq__NbFHq68WBMdljkCuuVfjIw {
	NI len;
	NI cap;
	tyTuple__N4J9cV4JZGem3ljqqj5rT0Q* d;
};
struct tyObject_CellSeq__MZ3vrnJoRJ9cOe8aQ89bLCEQ {
	NI len;
	NI cap;
	tyTuple__v8m6PEFL3KMh2a55VJabyg* d;
};
struct tyObject_GcEnv__YZbBpAB7y9bEm9a6qzlH6rdw {
	tyObject_CellSeq__NbFHq68WBMdljkCuuVfjIw traceStack;
	tyObject_CellSeq__MZ3vrnJoRJ9cOe8aQ89bLCEQ toFree;
	NI freed;
	NI touched;
	NI edges;
	NI rcSum;
	NIM_BOOL keepThreshold;
};
struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q {
void** Field0;
TNimTypeV2* Field1;
};
typedef tyEnum_GLerrorCode__9aa0fSh3zKRU4fPbvvwy9bOg tyArray__kFunyAB7cPB4n3kNDf9apVA[9];
struct tyObject_StackTraceEntry__AolQsxmhMZzaZBPezNXohw {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__LaG9a3ln9cHpAtM2PoiEBtMA_Content { NI cap; tyObject_StackTraceEntry__AolQsxmhMZzaZBPezNXohw data[SEQ_DECL_SIZE]; };
N_STDCALL(void, glViewport)(NI32 x_p0, NI32 y_p1, NI32 width_p2, NI32 height_p3);
N_LIB_PRIVATE N_NIMCALL(void, checkGLerror__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u359)(void);
N_LIB_PRIVATE N_NIMCALL(tyEnum_GLerrorCode__9aa0fSh3zKRU4fPbvvwy9bOg, getGLerrorCode__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u336)(void);
N_STDCALL(NU32, glGetError)(void);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u378)(tyObject_GLerror__pecJ3qrtkP9cNFDFcCVFvuA* dest_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_GLerror__pecJ3qrtkP9cNFDFcCVFvuA*, new__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u366)(void);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u30426)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u398)(tyObject_GLerror__pecJ3qrtkP9cNFDFcCVFvuA* dest_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u810)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__system_u3487)(NIM_BOOL isDestroyAction_p0, tyObject_RefHeader__m5DjWPRDLSOOpTFPKmlVBA* s_p1, TNimTypeV2* desc_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZassertions_u91)(tySequence__LaG9a3ln9cHpAtM2PoiEBtMA dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u410)(tyObject_GLerror__pecJ3qrtkP9cNFDFcCVFvuA* dest_p0, void* env_p1);
static N_INLINE(void, nimTraceRefDyn)(void* q_p0, void* env_p1);
static N_INLINE(void, add__system_u2951)(tyObject_CellSeq__NbFHq68WBMdljkCuuVfjIw* s_p0, void** c_p1, TNimTypeV2* t_p2);
N_LIB_PRIVATE N_NIMCALL(void, resize__system_u2959)(tyObject_CellSeq__NbFHq68WBMdljkCuuVfjIw* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___stdZassertions_u36)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1750)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u332)(tyEnum_GLerrorCode__9aa0fSh3zKRU4fPbvvwy9bOg e_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
static N_INLINE(void, nimMarkCyclic)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u375)(tyObject_GLerror__pecJ3qrtkP9cNFDFcCVFvuA** dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
N_STDCALL(void, glClearColor)(NF32 red_p0, NF32 green_p1, NF32 blue_p2, NF32 alpha_p3);
N_STDCALL(void, glClear)(NU32 mask_p0);
N_STDCALL(NU32, glCreateShader)(NU32 type_p0);
N_STDCALL(void, glShaderSource)(NU32 shader_p0, NI32 count_p1, NCSTRING* string_p2, NI32* length_p3);
N_STDCALL(void, glCompileShader)(NU32 shader_p0);
N_STDCALL(void, glGetShaderiv)(NU32 shader_p0, NU32 pname_p1, NI32* params_p2);
N_STDCALL(void, glGetShaderInfoLog)(NU32 shader_p0, NI32 bufSize_p1, NI32* length_p2, NCSTRING infoLog_p3);
N_STDCALL(void, glDeleteShader)(NU32 shader_p0);
N_STDCALL(NU32, glCreateProgram)(void);
N_STDCALL(void, glAttachShader)(NU32 program_p0, NU32 shader_p1);
N_STDCALL(void, glBindAttribLocation)(NU32 program_p0, NU32 index_p1, NCSTRING name_p2);
N_STDCALL(void, glLinkProgram)(NU32 program_p0);
N_STDCALL(void, glUseProgram)(NU32 program_p0);
N_STDCALL(void, glGenBuffers)(NI32 n_p0, NU32* buffers_p1);
N_STDCALL(void, glBindBuffer)(NU32 target_p0, NU32 buffer_p1);
N_STDCALL(void, glEnableVertexAttribArray)(NU32 index_p0);
N_STDCALL(void, glVertexAttribPointer)(NU32 index_p0, NI32 size_p1, NU32 type_p2, NIM_BOOL normalized_p3, NI32 stride_p4, void* pointer_p5);
N_STDCALL(void, glBufferData)(NU32 target_p0, NI size_p1, void* data_p2, NU32 usage_p3);
N_STDCALL(void, glDrawArrays)(NU32 mode_p0, NI32 first_p1, NI32 count_p2);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
N_LIB_PRIVATE TNimTypeV2 NTIv2__pecJ3qrtkP9cNFDFcCVFvuA_;
static const struct {
  NI cap; NIM_CHAR data[14+1];
} TM__5OHv4B5juaNW3eJpx9bSMRg_3 = { 14 | NIM_STRLIT_FLAG, "OpenGL error: " };
static const NimStringV2 TM__5OHv4B5juaNW3eJpx9bSMRg_4 = {14, (NimStrPayload*)&TM__5OHv4B5juaNW3eJpx9bSMRg_3};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__5OHv4B5juaNW3eJpx9bSMRg_5 = { 8 | NIM_STRLIT_FLAG, "no error" };
static const NimStringV2 TM__5OHv4B5juaNW3eJpx9bSMRg_6 = {8, (NimStrPayload*)&TM__5OHv4B5juaNW3eJpx9bSMRg_5};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__5OHv4B5juaNW3eJpx9bSMRg_7 = { 12 | NIM_STRLIT_FLAG, "invalid enum" };
static const NimStringV2 TM__5OHv4B5juaNW3eJpx9bSMRg_8 = {12, (NimStrPayload*)&TM__5OHv4B5juaNW3eJpx9bSMRg_7};
static const struct {
  NI cap; NIM_CHAR data[13+1];
} TM__5OHv4B5juaNW3eJpx9bSMRg_9 = { 13 | NIM_STRLIT_FLAG, "invalid value" };
static const NimStringV2 TM__5OHv4B5juaNW3eJpx9bSMRg_10 = {13, (NimStrPayload*)&TM__5OHv4B5juaNW3eJpx9bSMRg_9};
static const struct {
  NI cap; NIM_CHAR data[17+1];
} TM__5OHv4B5juaNW3eJpx9bSMRg_11 = { 17 | NIM_STRLIT_FLAG, "invalid operation" };
static const NimStringV2 TM__5OHv4B5juaNW3eJpx9bSMRg_12 = {17, (NimStrPayload*)&TM__5OHv4B5juaNW3eJpx9bSMRg_11};
static const struct {
  NI cap; NIM_CHAR data[14+1];
} TM__5OHv4B5juaNW3eJpx9bSMRg_13 = { 14 | NIM_STRLIT_FLAG, "stack overflow" };
static const NimStringV2 TM__5OHv4B5juaNW3eJpx9bSMRg_14 = {14, (NimStrPayload*)&TM__5OHv4B5juaNW3eJpx9bSMRg_13};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__5OHv4B5juaNW3eJpx9bSMRg_15 = { 15 | NIM_STRLIT_FLAG, "stack underflow" };
static const NimStringV2 TM__5OHv4B5juaNW3eJpx9bSMRg_16 = {15, (NimStrPayload*)&TM__5OHv4B5juaNW3eJpx9bSMRg_15};
static const struct {
  NI cap; NIM_CHAR data[13+1];
} TM__5OHv4B5juaNW3eJpx9bSMRg_17 = { 13 | NIM_STRLIT_FLAG, "out of memory" };
static const NimStringV2 TM__5OHv4B5juaNW3eJpx9bSMRg_18 = {13, (NimStrPayload*)&TM__5OHv4B5juaNW3eJpx9bSMRg_17};
static const struct {
  NI cap; NIM_CHAR data[29+1];
} TM__5OHv4B5juaNW3eJpx9bSMRg_19 = { 29 | NIM_STRLIT_FLAG, "invalid framebuffer operation" };
static const NimStringV2 TM__5OHv4B5juaNW3eJpx9bSMRg_20 = {29, (NimStrPayload*)&TM__5OHv4B5juaNW3eJpx9bSMRg_19};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__5OHv4B5juaNW3eJpx9bSMRg_21 = { 15 | NIM_STRLIT_FLAG, "table too large" };
static const NimStringV2 TM__5OHv4B5juaNW3eJpx9bSMRg_22 = {15, (NimStrPayload*)&TM__5OHv4B5juaNW3eJpx9bSMRg_21};
static const struct {
  NI cap; NIM_CHAR data[23+1];
} TM__5OHv4B5juaNW3eJpx9bSMRg_23 = { 23 | NIM_STRLIT_FLAG, "OpenGL error: unknown (" };
static const NimStringV2 TM__5OHv4B5juaNW3eJpx9bSMRg_24 = {23, (NimStrPayload*)&TM__5OHv4B5juaNW3eJpx9bSMRg_23};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__5OHv4B5juaNW3eJpx9bSMRg_25 = { 1 | NIM_STRLIT_FLAG, ")" };
static const NimStringV2 TM__5OHv4B5juaNW3eJpx9bSMRg_26 = {1, (NimStrPayload*)&TM__5OHv4B5juaNW3eJpx9bSMRg_25};
N_LIB_PRIVATE NIM_CONST tyArray__kFunyAB7cPB4n3kNDf9apVA AllErrorCodes__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u335 = {((tyEnum_GLerrorCode__9aa0fSh3zKRU4fPbvvwy9bOg)0),
((tyEnum_GLerrorCode__9aa0fSh3zKRU4fPbvvwy9bOg)1280),
((tyEnum_GLerrorCode__9aa0fSh3zKRU4fPbvvwy9bOg)1281),
((tyEnum_GLerrorCode__9aa0fSh3zKRU4fPbvvwy9bOg)1282),
((tyEnum_GLerrorCode__9aa0fSh3zKRU4fPbvvwy9bOg)1283),
((tyEnum_GLerrorCode__9aa0fSh3zKRU4fPbvvwy9bOg)1284),
((tyEnum_GLerrorCode__9aa0fSh3zKRU4fPbvvwy9bOg)1285),
((tyEnum_GLerrorCode__9aa0fSh3zKRU4fPbvvwy9bOg)1286),
((tyEnum_GLerrorCode__9aa0fSh3zKRU4fPbvvwy9bOg)32817)}
;
N_LIB_PRIVATE NIM_BOOL gAutoGLerrorCheck__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u514 = NIM_TRUE;
N_LIB_PRIVATE NIM_BOOL gInsideBeginEnd__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u515 = NIM_FALSE;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4345;
static NIM_CONST NU32 TM__5OHv4B5juaNW3eJpx9bSMRg_2[3] = {3701606400, 1285336064, 3876183552};
N_LIB_PRIVATE TNimTypeV2 NTIv2__pecJ3qrtkP9cNFDFcCVFvuA_ = {.destructor = (void*)rttiDestroy__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u30426, .size = sizeof(tyObject_GLerror__pecJ3qrtkP9cNFDFcCVFvuA), .align = (NI16) NIM_ALIGNOF(tyObject_GLerror__pecJ3qrtkP9cNFDFcCVFvuA), .depth = 2, .display = TM__5OHv4B5juaNW3eJpx9bSMRg_2, .name = "opengl.opengl.GLerror", .traceImpl = (void*)eqtrace___OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u410, .flags = 0};
N_LIB_PRIVATE N_NIMCALL(tyEnum_GLerrorCode__9aa0fSh3zKRU4fPbvvwy9bOg, getGLerrorCode__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u336)(void) {
	tyEnum_GLerrorCode__9aa0fSh3zKRU4fPbvvwy9bOg result;
	NU32 T1_;
	T1_ = (NU32)0;
	T1_ = glGetError();
	result = ((tyEnum_GLerrorCode__9aa0fSh3zKRU4fPbvvwy9bOg) (T1_));
	return result;
}
static N_INLINE(NI, minuspercent___system_u810)(NI x_p0, NI y_p1) {
	NI result;
	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4345);
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0) {
	NIM_BOOL result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	{
		tyObject_RefHeader__m5DjWPRDLSOOpTFPKmlVBA* cell;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		T5_ = (NI)0;
		T5_ = minuspercent___system_u810(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
		cell = ((tyObject_RefHeader__m5DjWPRDLSOOpTFPKmlVBA*) (T5_));
		{
			if (!((NI)((*cell).rc & ((NI)-16)) == ((NI)0))) goto LA8_;
			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			(*cell).rc -= ((NI)16);
		}
LA6_: ;
		rememberCycle__system_u3487(result, cell, (*((TNimTypeV2**) (p_p0))));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u398)(tyObject_GLerror__pecJ3qrtkP9cNFDFcCVFvuA* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.parent);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.parent);
	}
LA4_: ;
	if ((*dest_p0).Sup.message.p && !((*dest_p0).Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.message.p);
}
	eqdestroy___stdZassertions_u91((*dest_p0).Sup.trace);
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.up);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.up);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u30426)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u398(((tyObject_GLerror__pecJ3qrtkP9cNFDFcCVFvuA*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, add__system_u2951)(tyObject_CellSeq__NbFHq68WBMdljkCuuVfjIw* s_p0, void** c_p1, TNimTypeV2* t_p2) {
	void** colontmp_;
	TNimTypeV2* colontmp__2;
	{
		if (!((*s_p0).cap <= (*s_p0).len)) goto LA3_;
		resize__system_u2959(s_p0);
	}
LA3_: ;
	colontmp_ = c_p1;
	colontmp__2 = t_p2;
	(*s_p0).d[(*s_p0).len].Field0 = colontmp_;
	(*s_p0).d[(*s_p0).len].Field1 = colontmp__2;
	(*s_p0).len += ((NI)1);
}
static N_INLINE(void, nimTraceRefDyn)(void* q_p0, void* env_p1) {
	void** p;
	p = ((void**) (q_p0));
	{
		tyObject_GcEnv__YZbBpAB7y9bEm9a6qzlH6rdw* j;
		if (!!(((*p) == NIM_NIL))) goto LA3_;
		j = ((tyObject_GcEnv__YZbBpAB7y9bEm9a6qzlH6rdw*) (env_p1));
		add__system_u2951((&(*j).traceStack), p, (*((TNimTypeV2**) ((*p)))));
	}
LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u410)(tyObject_GLerror__pecJ3qrtkP9cNFDFcCVFvuA* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.up, env_p1);
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1750)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
	{
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		copyMem__system_u1750(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), ((NI) ((NI)(src_p1.len + ((NI)1)))));
		(*dest_p0).len += src_p1.len;
	}
LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u332)(tyEnum_GLerrorCode__9aa0fSh3zKRU4fPbvvwy9bOg e_p0) {
	NimStringV2 result;
	switch (e_p0) {
	case ((tyEnum_GLerrorCode__9aa0fSh3zKRU4fPbvvwy9bOg)0):
	{
		result = TM__5OHv4B5juaNW3eJpx9bSMRg_6;
	}
	break;
	case ((tyEnum_GLerrorCode__9aa0fSh3zKRU4fPbvvwy9bOg)1280):
	{
		result = TM__5OHv4B5juaNW3eJpx9bSMRg_8;
	}
	break;
	case ((tyEnum_GLerrorCode__9aa0fSh3zKRU4fPbvvwy9bOg)1281):
	{
		result = TM__5OHv4B5juaNW3eJpx9bSMRg_10;
	}
	break;
	case ((tyEnum_GLerrorCode__9aa0fSh3zKRU4fPbvvwy9bOg)1282):
	{
		result = TM__5OHv4B5juaNW3eJpx9bSMRg_12;
	}
	break;
	case ((tyEnum_GLerrorCode__9aa0fSh3zKRU4fPbvvwy9bOg)1283):
	{
		result = TM__5OHv4B5juaNW3eJpx9bSMRg_14;
	}
	break;
	case ((tyEnum_GLerrorCode__9aa0fSh3zKRU4fPbvvwy9bOg)1284):
	{
		result = TM__5OHv4B5juaNW3eJpx9bSMRg_16;
	}
	break;
	case ((tyEnum_GLerrorCode__9aa0fSh3zKRU4fPbvvwy9bOg)1285):
	{
		result = TM__5OHv4B5juaNW3eJpx9bSMRg_18;
	}
	break;
	case ((tyEnum_GLerrorCode__9aa0fSh3zKRU4fPbvvwy9bOg)1286):
	{
		result = TM__5OHv4B5juaNW3eJpx9bSMRg_20;
	}
	break;
	case ((tyEnum_GLerrorCode__9aa0fSh3zKRU4fPbvvwy9bOg)32817):
	{
		result = TM__5OHv4B5juaNW3eJpx9bSMRg_22;
	}
	break;
	default: __builtin_unreachable();
	}
	return result;
}
static N_INLINE(void, nimMarkCyclic)(void* p_p0) {
}
N_LIB_PRIVATE N_NIMCALL(void, checkGLerror__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u359)(void) {
	tyObject_GLerror__pecJ3qrtkP9cNFDFcCVFvuA* exc;
	NimStringV2 colontmpD_;
	tyEnum_GLerrorCode__9aa0fSh3zKRU4fPbvvwy9bOg error;
	NimStringV2 T21_;
	tyObject_GLerror__pecJ3qrtkP9cNFDFcCVFvuA* blitTmp_2;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	exc = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	error = getGLerrorCode__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u336();
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		if (!(error == ((tyEnum_GLerrorCode__9aa0fSh3zKRU4fPbvvwy9bOg)0))) goto LA4_;
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		eqdestroy___OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u378(exc);
		goto BeforeRet_;
	}
LA4_: ;
	exc = new__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u366();
	{
		tyEnum_GLerrorCode__9aa0fSh3zKRU4fPbvvwy9bOg e;
		NI i;
		e = (tyEnum_GLerrorCode__9aa0fSh3zKRU4fPbvvwy9bOg)0;
		i = ((NI)0);
		{
			while (1) {
				e = AllErrorCodes__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u335[(i)- 0];
				{
					NimStringV2 colontmpD__2;
					NimStringV2 T14_;
					tyObject_GLerror__pecJ3qrtkP9cNFDFcCVFvuA* blitTmp;
					if (!(e == error)) goto LA11_;
					colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
					T14_.len = 0; T14_.p = NIM_NIL;
					colontmpD__2 = dollar___OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u332(e);
					T14_ = rawNewString(colontmpD__2.len + 14);
appendString((&T14_), TM__5OHv4B5juaNW3eJpx9bSMRg_4);
appendString((&T14_), colontmpD__2);
					eqsink___stdZassertions_u36((&(*exc).Sup.message), T14_);
					blitTmp = exc;
					nimMarkCyclic(exc);
					eqwasMoved___OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u375(&exc);
					raiseExceptionEx((Exception*)blitTmp, "GLerror", "checkGLerror", "errors.nim", 99);
goto LA13_;
					{
						LA13_:;
					}
					{
						if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
					}
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				}
LA11_: ;
				{
					if (!(((NI)8) <= ((NI) (i)))) goto LA19_;
					goto LA7;
				}
LA19_: ;
				i += ((NI)1);
			}
		} LA7: ;
	}
	(*exc).code = error;
	T21_.len = 0; T21_.p = NIM_NIL;
	colontmpD_ = dollar___OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u332(error);
	T21_ = rawNewString(colontmpD_.len + 24);
appendString((&T21_), TM__5OHv4B5juaNW3eJpx9bSMRg_24);
appendString((&T21_), colontmpD_);
appendString((&T21_), TM__5OHv4B5juaNW3eJpx9bSMRg_26);
	eqsink___stdZassertions_u36((&(*exc).Sup.message), T21_);
	blitTmp_2 = exc;
	nimMarkCyclic(exc);
	eqwasMoved___OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u375(&exc);
	raiseExceptionEx((Exception*)blitTmp_2, "GLerror", "checkGLerror", "errors.nim", 103);
goto LA1_;
	{
		LA1_:;
	}
	{
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		eqdestroy___OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u378(exc);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_STDCALL(void, glViewport__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u21906)(NI32 x_p0, NI32 y_p1, NI32 width_p2, NI32 height_p3) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	glViewport(x_p0, y_p1, width_p2, height_p3);
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u514;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u515);
LA4_: ;
		if (!T3_) goto LA5_;
		checkGLerror__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u359();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA5_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_STDCALL(void, glClearColor__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u7812)(NF32 red_p0, NF32 green_p1, NF32 blue_p2, NF32 alpha_p3) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	glClearColor(red_p0, green_p1, blue_p2, alpha_p3);
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u514;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u515);
LA4_: ;
		if (!T3_) goto LA5_;
		checkGLerror__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u359();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA5_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_STDCALL(void, glClear__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u17007)(NU32 mask_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	glClear(mask_p0);
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u514;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u515);
LA4_: ;
		if (!T3_) goto LA5_;
		checkGLerror__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u359();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA5_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_STDCALL(NU32, glCreateShader__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u1183)(NU32 type_p0) {
	NU32 result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = glCreateShader(type_p0);
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u514;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u515);
LA4_: ;
		if (!T3_) goto LA5_;
		checkGLerror__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u359();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA5_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_STDCALL(void, glShaderSource__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u10860)(NU32 shader_p0, NI32 count_p1, NCSTRING* string_p2, NI32* length_p3) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	glShaderSource(shader_p0, count_p1, string_p2, length_p3);
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u514;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u515);
LA4_: ;
		if (!T3_) goto LA5_;
		checkGLerror__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u359();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA5_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_STDCALL(void, glCompileShader__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u3832)(NU32 shader_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	glCompileShader(shader_p0);
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u514;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u515);
LA4_: ;
		if (!T3_) goto LA5_;
		checkGLerror__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u359();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA5_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_STDCALL(void, glGetShaderiv__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u9571)(NU32 shader_p0, NU32 pname_p1, NI32* params_p2) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	glGetShaderiv(shader_p0, pname_p1, params_p2);
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u514;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u515);
LA4_: ;
		if (!T3_) goto LA5_;
		checkGLerror__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u359();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA5_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_STDCALL(void, glGetShaderInfoLog__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u13650)(NU32 shader_p0, NI32 bufSize_p1, NI32* length_p2, NCSTRING infoLog_p3) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	glGetShaderInfoLog(shader_p0, bufSize_p1, length_p2, infoLog_p3);
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u514;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u515);
LA4_: ;
		if (!T3_) goto LA5_;
		checkGLerror__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u359();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA5_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_STDCALL(void, glDeleteShader__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u20728)(NU32 shader_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	glDeleteShader(shader_p0);
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u514;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u515);
LA4_: ;
		if (!T3_) goto LA5_;
		checkGLerror__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u359();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA5_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_STDCALL(NU32, glCreateProgram__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u19040)(void) {
	NU32 result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = glCreateProgram();
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u514;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u515);
LA4_: ;
		if (!T3_) goto LA5_;
		checkGLerror__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u359();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA5_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_STDCALL(void, glAttachShader__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u3402)(NU32 program_p0, NU32 shader_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	glAttachShader(program_p0, shader_p1);
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u514;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u515);
LA4_: ;
		if (!T3_) goto LA5_;
		checkGLerror__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u359();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA5_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_STDCALL(void, glBindAttribLocation__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u24209)(NU32 program_p0, NU32 index_p1, NCSTRING name_p2) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	glBindAttribLocation(program_p0, index_p1, name_p2);
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u514;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u515);
LA4_: ;
		if (!T3_) goto LA5_;
		checkGLerror__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u359();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA5_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_STDCALL(void, glLinkProgram__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u2128)(NU32 program_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	glLinkProgram(program_p0);
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u514;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u515);
LA4_: ;
		if (!T3_) goto LA5_;
		checkGLerror__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u359();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA5_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_STDCALL(void, glUseProgram__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u14310)(NU32 program_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	glUseProgram(program_p0);
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u514;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u515);
LA4_: ;
		if (!T3_) goto LA5_;
		checkGLerror__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u359();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA5_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_STDCALL(void, glGenBuffers__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u8304)(NI32 n_p0, NU32* buffers_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	glGenBuffers(n_p0, buffers_p1);
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u514;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u515);
LA4_: ;
		if (!T3_) goto LA5_;
		checkGLerror__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u359();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA5_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_STDCALL(void, glBindBuffer__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u914)(NU32 target_p0, NU32 buffer_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	glBindBuffer(target_p0, buffer_p1);
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u514;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u515);
LA4_: ;
		if (!T3_) goto LA5_;
		checkGLerror__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u359();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA5_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_STDCALL(void, glEnableVertexAttribArray__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u20888)(NU32 index_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	glEnableVertexAttribArray(index_p0);
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u514;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u515);
LA4_: ;
		if (!T3_) goto LA5_;
		checkGLerror__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u359();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA5_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_STDCALL(void, glVertexAttribPointer__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u11864)(NU32 index_p0, NI32 size_p1, NU32 type_p2, NIM_BOOL normalized_p3, NI32 stride_p4, void* pointer_p5) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	glVertexAttribPointer(index_p0, size_p1, type_p2, normalized_p3, stride_p4, pointer_p5);
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u514;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u515);
LA4_: ;
		if (!T3_) goto LA5_;
		checkGLerror__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u359();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA5_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_STDCALL(void, glBufferData__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u10101)(NU32 target_p0, NI size_p1, void* data_p2, NU32 usage_p3) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	glBufferData(target_p0, size_p1, data_p2, usage_p3);
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u514;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u515);
LA4_: ;
		if (!T3_) goto LA5_;
		checkGLerror__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u359();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA5_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_STDCALL(void, glDrawArrays__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u13759)(NU32 mode_p0, NI32 first_p1, NI32 count_p2) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	glDrawArrays(mode_p0, first_p1, count_p2);
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u514;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u515);
LA4_: ;
		if (!T3_) goto LA5_;
		checkGLerror__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u359();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA5_: ;
	}BeforeRet_: ;
}
