/* Generated by Nim Compiler v2.0.8 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ tySequence__6H5Oh5UUvVCLiakt9aTwtUQ;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_ExampleApp__8z417nKvwMPZkrWnJ5WRJQ tyObject_ExampleApp__8z417nKvwMPZkrWnJ5WRJQ;
typedef struct tySequence__4Xyxy0Om14N6K1l5e9bUPSQ tySequence__4Xyxy0Om14N6K1l5e9bUPSQ;
typedef struct tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content;
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ {
  NI len; tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content* p;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyObject_ExampleApp__8z417nKvwMPZkrWnJ5WRJQ {
	NU32 program;
	NU32 vertexBuffer;
	double lastTouchX;
	double lastTouchY;
	double offsetX;
	double offsetY;
};
typedef NimStringV2 tyArray__nHXaesL0DJZHyVS07ARPRA[1];
typedef NU8 tyEnum_GLFMRenderingAPI__X9cPQp6TMCe7CyGitWYnmFQ;
typedef NU8 tyEnum_GLFMColorFormat__B5oVFc9a9bleZEcxsprXxuGQ;
typedef NU8 tyEnum_GLFMDepthFormat__7cjWm8ekVbrcorhokDJT9aQ;
typedef NU8 tyEnum_GLFMStencilFormat__qQnIOhnCNoFb7KzllnQU8w;
typedef NU8 tyEnum_GLFMMultisample__LKoPnOwXYDp1HTCRyATojQ;
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void** display_p0, int width_p1, int height_p2, void* ClE_0);
void* ClE_0;
} tyProc__d0tzLLq7AbEObpKtlZImpA;
typedef N_CLOSURE_PTR(void, TM__59aBxGWp6q9aemWfj0Y3wGlA_6) (void** display_p0, int width_p1, int height_p2, void* ClE_0);
typedef N_CLOSURE_PTR(void, TM__59aBxGWp6q9aemWfj0Y3wGlA_7) (void** display_p0, int width_p1, int height_p2, void* ClE_0);
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void** display_p0, void* ClE_0);
void* ClE_0;
} tyProc__OWoMzYmTKPUvWrQhzvWLBA;
typedef N_CLOSURE_PTR(void, TM__59aBxGWp6q9aemWfj0Y3wGlA_8) (void** display_p0, void* ClE_0);
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void** display_p0, double frameTime_p1, void* ClE_0);
void* ClE_0;
} tyProc__B38YaKbIJZkI8xoQ6zVwxQ;
struct tySequence__4Xyxy0Om14N6K1l5e9bUPSQ {
  NI len; tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content* p;
};
typedef NCSTRING tyArray__NmEsK2qSxmxyFA4fWeYieg[1];
typedef NimStringV2 tyArray__Re75IspeoxXy2oCZHwcRrA[2];
typedef N_CLOSURE_PTR(void, TM__59aBxGWp6q9aemWfj0Y3wGlA_30) (void** display_p0, double frameTime_p1, void* ClE_0);
typedef NU8 tyEnum_GLFMTouchPhase__ClxE9ajyzPj3mn2CrAmSDdw;
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (void** display_p0, int touch_p1, tyEnum_GLFMTouchPhase__ClxE9ajyzPj3mn2CrAmSDdw phase_p2, double x_p3, double y_p4, void* ClE_0);
void* ClE_0;
} tyProc__bQ863fx7S8H7f1ucLoHUQw;
typedef NimStringV2 tyArray__sMpvt1sOxOJ3LFGulnbeMQ[4];
typedef N_CLOSURE_PTR(NIM_BOOL, TM__59aBxGWp6q9aemWfj0Y3wGlA_35) (void** display_p0, int touch_p1, tyEnum_GLFMTouchPhase__ClxE9ajyzPj3mn2CrAmSDdw phase_p2, double x_p3, double y_p4, void* ClE_0);
typedef NU16 tyEnum_GLFMKey__GrBAa2tzG9ajXYl9bCEity1w;
typedef NU8 tyEnum_GLFMKeyAction__YTIfOfrNucIeZ9bSR9bZFUNw;
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (void** display_p0, tyEnum_GLFMKey__GrBAa2tzG9ajXYl9bCEity1w keyCode_p1, tyEnum_GLFMKeyAction__YTIfOfrNucIeZ9bSR9bZFUNw action_p2, int modifiers_p3, void* ClE_0);
void* ClE_0;
} tyProc__XLpcabov1HBFAn7gm9cb8hQ;
typedef N_CLOSURE_PTR(NIM_BOOL, TM__59aBxGWp6q9aemWfj0Y3wGlA_36) (void** display_p0, tyEnum_GLFMKey__GrBAa2tzG9ajXYl9bCEity1w keyCode_p1, tyEnum_GLFMKeyAction__YTIfOfrNucIeZ9bSR9bZFUNw action_p2, int modifiers_p3, void* ClE_0);
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content { NI cap; NU8 data[SEQ_DECL_SIZE]; };
struct tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content { NI cap; NF32 data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void, glfmMain)(void** display_p0);
N_NIMCALL(void, NimMain)(void);
N_LIB_PRIVATE N_NIMCALL(void, echoBinSafe)(NimStringV2* args_p0, NI args_p0Len_0);
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, newSeq__main_u130)(NI len_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u8)(NI x_p0);
N_NIMCALL(void, glfmSetDisplayConfig)(void** display_p0, tyEnum_GLFMRenderingAPI__X9cPQp6TMCe7CyGitWYnmFQ preferredAPI_p1, tyEnum_GLFMColorFormat__B5oVFc9a9bleZEcxsprXxuGQ colorFormat_p2, tyEnum_GLFMDepthFormat__7cjWm8ekVbrcorhokDJT9aQ depthFormat_p3, tyEnum_GLFMStencilFormat__qQnIOhnCNoFb7KzllnQU8w stencilFormat_p4, tyEnum_GLFMMultisample__LKoPnOwXYDp1HTCRyATojQ multisample_p5);
N_NIMCALL(void, glfmSetUserData)(void** display_p0, void* userData_p1);
N_NIMCALL(void, glfmSetSurfaceCreatedFunc)(void** display_p0, tyProc__d0tzLLq7AbEObpKtlZImpA surfaceCreatedFunc_p1);
N_LIB_PRIVATE N_NIMCALL(void, onSurfaceCreated__main_u13)(void** display_p0, int width_p1, int height_p2);
N_LIB_PRIVATE N_STDCALL(void, glViewport__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u21906)(NI32 x_p0, NI32 y_p1, NI32 width_p2, NI32 height_p3);
N_NIMCALL(tyEnum_GLFMRenderingAPI__X9cPQp6TMCe7CyGitWYnmFQ, glfmGetRenderingAPI)(void** display_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
N_NIMCALL(void, glfmSetSurfaceResizedFunc)(void** display_p0, tyProc__d0tzLLq7AbEObpKtlZImpA surfaceResizedFunc_p1);
N_NIMCALL(void, glfmSetSurfaceDestroyedFunc)(void** display_p0, tyProc__OWoMzYmTKPUvWrQhzvWLBA surfaceDestroyedFunc_p1);
N_LIB_PRIVATE N_NIMCALL(void, onSurfaceDestroyed__main_u17)(void** display_p0);
N_NIMCALL(void, glfmSetMainLoopFunc)(void** display_p0, tyProc__B38YaKbIJZkI8xoQ6zVwxQ mainLoopFunc_p1);
N_LIB_PRIVATE N_NIMCALL(void, onFrame__main_u10)(void** display_p0, double frameTime_p1);
N_LIB_PRIVATE N_STDCALL(void, glClearColor__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u7812)(NF32 red_p0, NF32 green_p1, NF32 blue_p2, NF32 alpha_p3);
N_LIB_PRIVATE N_STDCALL(void, glClear__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u17007)(NU32 mask_p0);
N_LIB_PRIVATE N_NIMCALL(NU32, compileShader__main_u615)(NU32 type_p0, NimStringV2 shaderString_p1);
N_LIB_PRIVATE N_STDCALL(NU32, glCreateShader__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u1183)(NU32 type_p0);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
N_LIB_PRIVATE N_STDCALL(void, glShaderSource__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u10860)(NU32 shader_p0, NI32 count_p1, NCSTRING* string_p2, NI32* length_p3);
N_LIB_PRIVATE N_STDCALL(void, glCompileShader__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u3832)(NU32 shader_p0);
N_LIB_PRIVATE N_STDCALL(void, glGetShaderiv__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u9571)(NU32 shader_p0, NU32 pname_p1, NI32* params_p2);
N_NIMCALL(NimStringV2, rawNewString)(NI cap_p0);
N_LIB_PRIVATE N_STDCALL(void, glGetShaderInfoLog__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u13650)(NU32 shader_p0, NI32 bufSize_p1, NI32* length_p2, NCSTRING infoLog_p3);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_STDCALL(void, glDeleteShader__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u20728)(NU32 shader_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___main_u738)(tySequence__4Xyxy0Om14N6K1l5e9bUPSQ dest_p0);
N_LIB_PRIVATE N_STDCALL(NU32, glCreateProgram__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u19040)(void);
N_LIB_PRIVATE N_STDCALL(void, glAttachShader__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u3402)(NU32 program_p0, NU32 shader_p1);
N_LIB_PRIVATE N_STDCALL(void, glBindAttribLocation__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u24209)(NU32 program_p0, NU32 index_p1, NCSTRING name_p2);
N_LIB_PRIVATE N_STDCALL(void, glLinkProgram__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u2128)(NU32 program_p0);
N_LIB_PRIVATE N_STDCALL(void, glUseProgram__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u14310)(NU32 program_p0);
N_LIB_PRIVATE N_STDCALL(void, glGenBuffers__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u8304)(NI32 n_p0, NU32* buffers_p1);
N_LIB_PRIVATE N_STDCALL(void, glBindBuffer__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u914)(NU32 target_p0, NU32 buffer_p1);
N_LIB_PRIVATE N_STDCALL(void, glEnableVertexAttribArray__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u20888)(NU32 index_p0);
N_LIB_PRIVATE N_STDCALL(void, glVertexAttribPointer__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u11864)(NU32 index_p0, NI32 size_p1, NU32 type_p2, NIM_BOOL normalized_p3, NI32 stride_p4, void* pointer_p5);
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap_p0, NI elemSize_p1, NI elemAlign_p2);
N_LIB_PRIVATE N_STDCALL(void, glBufferData__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u10101)(NU32 target_p0, NI size_p1, void* data_p2, NU32 usage_p3);
N_LIB_PRIVATE N_STDCALL(void, glDrawArrays__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u13759)(NU32 mode_p0, NI32 first_p1, NI32 count_p2);
N_NIMCALL(void, glfmSetTouchFunc)(void** display_p0, tyProc__bQ863fx7S8H7f1ucLoHUQw touchFunc_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, onTouch__main_u19)(void** display_p0, int touch_p1, tyEnum_GLFMTouchPhase__ClxE9ajyzPj3mn2CrAmSDdw phase_p2, double x_p3, double y_p4);
N_NIMCALL(void, glfmGetDisplaySize)(void** display_p0, int* width_p1, int* height_p2);
static N_INLINE(void, pluseq___main_u473)(double* x_p0, double y_p1);
static N_INLINE(void, minuseq___main_u477)(double* x_p0, double y_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___main_u490)(double x_p0);
N_NIMCALL(void, glfmSetKeyFunc)(void** display_p0, tyProc__XLpcabov1HBFAn7gm9cb8hQ keyFunc_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, onKey__main_u25)(void** display_p0, tyEnum_GLFMKey__GrBAa2tzG9ajXYl9bCEity1w keyCode_p1, tyEnum_GLFMKeyAction__YTIfOfrNucIeZ9bSR9bZFUNw action_p2, int modifiers_p3);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___main_u141)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void);
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__59aBxGWp6q9aemWfj0Y3wGlA_3 = { 15 | NIM_STRLIT_FLAG, "test allocation" };
static const struct {
  NI cap; NIM_CHAR data[20+1];
} TM__59aBxGWp6q9aemWfj0Y3wGlA_5 = { 20 | NIM_STRLIT_FLAG, "done allocation test" };
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__59aBxGWp6q9aemWfj0Y3wGlA_10 = { 5 | NIM_STRLIT_FLAG, "setup" };
static const struct {
  NI cap; NIM_CHAR data[17+1];
} TM__59aBxGWp6q9aemWfj0Y3wGlA_12 = { 17 | NIM_STRLIT_FLAG, "glShaderSource..." };
static const struct {
  NI cap; NIM_CHAR data[18+1];
} TM__59aBxGWp6q9aemWfj0Y3wGlA_14 = { 18 | NIM_STRLIT_FLAG, "glCompileShader..." };
static const struct {
  NI cap; NIM_CHAR data[29+1];
} TM__59aBxGWp6q9aemWfj0Y3wGlA_16 = { 29 | NIM_STRLIT_FLAG, "So... Couldn\'t compile shader" };
static const struct {
  NI cap; NIM_CHAR data[32+1];
} TM__59aBxGWp6q9aemWfj0Y3wGlA_18 = { 32 | NIM_STRLIT_FLAG, "glGetShaderiv GL_INFO_LOG_LENGTH" };
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__59aBxGWp6q9aemWfj0Y3wGlA_19 = { 10 | NIM_STRLIT_FLAG, "Log lengh " };
static const NimStringV2 TM__59aBxGWp6q9aemWfj0Y3wGlA_20 = {10, (NimStrPayload*)&TM__59aBxGWp6q9aemWfj0Y3wGlA_19};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__59aBxGWp6q9aemWfj0Y3wGlA_21 = { 12 | NIM_STRLIT_FLAG, "Shader log: " };
static const NimStringV2 TM__59aBxGWp6q9aemWfj0Y3wGlA_22 = {12, (NimStrPayload*)&TM__59aBxGWp6q9aemWfj0Y3wGlA_21};
static const struct {
  NI cap; NIM_CHAR data[171+1];
} TM__59aBxGWp6q9aemWfj0Y3wGlA_23 = { 171 | NIM_STRLIT_FLAG, "attribute highp vec3 a_position;\012attribute lowp vec3 a_color;\012\012varying lowp vec3 v_color;\012\012void main() {\012    gl_Position = vec4(a_position, 1.0);\012    v_color = a_color;\012}\012" };
static const NimStringV2 TM__59aBxGWp6q9aemWfj0Y3wGlA_24 = {171, (NimStrPayload*)&TM__59aBxGWp6q9aemWfj0Y3wGlA_23};
static const struct {
  NI cap; NIM_CHAR data[83+1];
} TM__59aBxGWp6q9aemWfj0Y3wGlA_25 = { 83 | NIM_STRLIT_FLAG, "varying lowp vec3 v_color;\012\012void main() {\012    gl_FragColor = vec4(v_color, 1.0);\012}\012" };
static const NimStringV2 TM__59aBxGWp6q9aemWfj0Y3wGlA_26 = {83, (NimStrPayload*)&TM__59aBxGWp6q9aemWfj0Y3wGlA_25};
static NIM_CONST tyProc__B38YaKbIJZkI8xoQ6zVwxQ TM__59aBxGWp6q9aemWfj0Y3wGlA_27 = {NIM_NIL,NIM_NIL};
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__59aBxGWp6q9aemWfj0Y3wGlA_29 = { 10 | NIM_STRLIT_FLAG, "setup done" };
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__59aBxGWp6q9aemWfj0Y3wGlA_31 = { 5 | NIM_STRLIT_FLAG, "touch" };
static const NimStringV2 TM__59aBxGWp6q9aemWfj0Y3wGlA_32 = {5, (NimStrPayload*)&TM__59aBxGWp6q9aemWfj0Y3wGlA_31};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__59aBxGWp6q9aemWfj0Y3wGlA_33 = { 1 | NIM_STRLIT_FLAG, " " };
static const NimStringV2 TM__59aBxGWp6q9aemWfj0Y3wGlA_34 = {1, (NimStrPayload*)&TM__59aBxGWp6q9aemWfj0Y3wGlA_33};
static const struct {
  NI cap; NIM_CHAR data[17+1];
} TM__59aBxGWp6q9aemWfj0Y3wGlA_38 = { 17 | NIM_STRLIT_FLAG, "test allocation 1" };
static const struct {
  NI cap; NIM_CHAR data[22+1];
} TM__59aBxGWp6q9aemWfj0Y3wGlA_40 = { 22 | NIM_STRLIT_FLAG, "done allocation test 1" };
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__59aBxGWp6q9aemWfj0Y3wGlA_2 = {{15, (NimStrPayload*)&TM__59aBxGWp6q9aemWfj0Y3wGlA_3}}
;
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__59aBxGWp6q9aemWfj0Y3wGlA_4 = {{20, (NimStrPayload*)&TM__59aBxGWp6q9aemWfj0Y3wGlA_5}}
;
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__59aBxGWp6q9aemWfj0Y3wGlA_9 = {{5, (NimStrPayload*)&TM__59aBxGWp6q9aemWfj0Y3wGlA_10}}
;
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__59aBxGWp6q9aemWfj0Y3wGlA_11 = {{17, (NimStrPayload*)&TM__59aBxGWp6q9aemWfj0Y3wGlA_12}}
;
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__59aBxGWp6q9aemWfj0Y3wGlA_13 = {{18, (NimStrPayload*)&TM__59aBxGWp6q9aemWfj0Y3wGlA_14}}
;
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__59aBxGWp6q9aemWfj0Y3wGlA_15 = {{29, (NimStrPayload*)&TM__59aBxGWp6q9aemWfj0Y3wGlA_16}}
;
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__59aBxGWp6q9aemWfj0Y3wGlA_17 = {{32, (NimStrPayload*)&TM__59aBxGWp6q9aemWfj0Y3wGlA_18}}
;
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__59aBxGWp6q9aemWfj0Y3wGlA_28 = {{10, (NimStrPayload*)&TM__59aBxGWp6q9aemWfj0Y3wGlA_29}}
;
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__59aBxGWp6q9aemWfj0Y3wGlA_37 = {{17, (NimStrPayload*)&TM__59aBxGWp6q9aemWfj0Y3wGlA_38}}
;
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__59aBxGWp6q9aemWfj0Y3wGlA_39 = {{22, (NimStrPayload*)&TM__59aBxGWp6q9aemWfj0Y3wGlA_40}}
;
N_LIB_PRIVATE tySequence__6H5Oh5UUvVCLiakt9aTwtUQ s__main_u902;
N_LIB_PRIVATE tyObject_ExampleApp__8z417nKvwMPZkrWnJ5WRJQ app__main_u30;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4345;
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4345);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, onSurfaceCreated__main_u13)(void** display_p0, int width_p1, int height_p2) {
	tyEnum_GLFMRenderingAPI__X9cPQp6TMCe7CyGitWYnmFQ api;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	glViewport__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u21906(((NI32)0), ((NI32)0), width_p1, height_p2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	api = glfmGetRenderingAPI(display_p0);
	}BeforeRet_: ;
}
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, onSurfaceDestroyed__main_u17)(void** display_p0) {
	app__main_u30.program = ((NU32)0);
	app__main_u30.vertexBuffer = ((NU32)0);
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU32, compileShader__main_u615)(NU32 type_p0, NimStringV2 shaderString_p1) {
	NU32 result;
	NU32 shader;
	tyArray__NmEsK2qSxmxyFA4fWeYieg shaderTextArr;
	NI32 status;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NU32)0;
	shader = glCreateShader__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u1183(type_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimZeroMem((void*)shaderTextArr, sizeof(tyArray__NmEsK2qSxmxyFA4fWeYieg));
	shaderTextArr[0] = nimToCStringConv(shaderString_p1);
	echoBinSafe(TM__59aBxGWp6q9aemWfj0Y3wGlA_11, 1);
	glShaderSource__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u10860(shader, ((NI32)1), ((NCSTRING*) (shaderTextArr)), ((NI32*) NIM_NIL));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	echoBinSafe(TM__59aBxGWp6q9aemWfj0Y3wGlA_13, 1);
	glCompileShader__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u3832(shader);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	status = (NI32)0;
	glGetShaderiv__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u9571(shader, ((NU32)35713), (&status));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NimStringV2 colontmpD_;
		NI32 logLength;
		tyArray__Re75IspeoxXy2oCZHwcRrA T6_;
		if (!(status == ((NI32)0))) goto LA3_;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		echoBinSafe(TM__59aBxGWp6q9aemWfj0Y3wGlA_15, 1);
		logLength = (NI32)0;
		echoBinSafe(TM__59aBxGWp6q9aemWfj0Y3wGlA_17, 1);
		glGetShaderiv__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u9571(shader, ((NU32)35716), (&logLength));
		if (NIM_UNLIKELY(*nimErr_)) goto LA5_;
		T6_[0] = TM__59aBxGWp6q9aemWfj0Y3wGlA_20;
		colontmpD_ = dollar___systemZdollars_u8(((NI) (logLength)));
		if (NIM_UNLIKELY(*nimErr_)) goto LA5_;
		T6_[1] = colontmpD_;
		echoBinSafe(T6_, 2);
		{
			NimStringV2 log;
			tyArray__Re75IspeoxXy2oCZHwcRrA T12_;
			if (!(((NI32)0) < logLength)) goto LA9_;
			log.len = 0; log.p = NIM_NIL;
			log = rawNewString(((NI) (logLength)));
			glGetShaderInfoLog__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u13650(shader, logLength, (&logLength), nimToCStringConv(log));
			if (NIM_UNLIKELY(*nimErr_)) goto LA11_;
			T12_[0] = TM__59aBxGWp6q9aemWfj0Y3wGlA_22;
			T12_[1] = log;
			echoBinSafe(T12_, 2);
			{
				LA11_:;
			}
			{
				if (log.p && !(log.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(log.p);
}
			}
			if (NIM_UNLIKELY(*nimErr_)) goto LA5_;
		}
LA9_: ;
		glDeleteShader__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u20728(shader);
		if (NIM_UNLIKELY(*nimErr_)) goto LA5_;
		shader = ((NU32)0);
		{
			LA5_:;
		}
		{
			if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	result = shader;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, onFrame__main_u10)(void** display_p0, double frameTime_p1) {
	tySequence__4Xyxy0Om14N6K1l5e9bUPSQ vertices;
	NI32 stride;
	NI T17_;
	NI T18_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	vertices.len = 0; vertices.p = NIM_NIL;
	glClearColor__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u7812(0.0f, 0.0f, 0.0f, 1.0f);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	glClear__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u17007(((NU32)16384));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		NU32 vertShader;
		NU32 fragShader;
		NU32 T12_;
		if (!(app__main_u30.program == ((NU32)0))) goto LA4_;
		echoBinSafe(TM__59aBxGWp6q9aemWfj0Y3wGlA_9, 1);
		vertShader = compileShader__main_u615(((NU32)35633), TM__59aBxGWp6q9aemWfj0Y3wGlA_24);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		fragShader = compileShader__main_u615(((NU32)35632), TM__59aBxGWp6q9aemWfj0Y3wGlA_26);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		{
			NIM_BOOL T8_;
			T8_ = (NIM_BOOL)0;
			T8_ = (vertShader == ((NU32)0));
			if (T8_) goto LA9_;
			T8_ = (fragShader == ((NU32)0));
LA9_: ;
			if (!T8_) goto LA10_;
			glfmSetMainLoopFunc(display_p0, TM__59aBxGWp6q9aemWfj0Y3wGlA_27);
			eqdestroy___main_u738(vertices);
			goto BeforeRet_;
		}
LA10_: ;
		T12_ = (NU32)0;
		T12_ = glCreateProgram__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u19040();
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		app__main_u30.program = T12_;
		glAttachShader__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u3402(app__main_u30.program, vertShader);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		glAttachShader__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u3402(app__main_u30.program, fragShader);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		glBindAttribLocation__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u24209(app__main_u30.program, ((NU32)0), "a_position");
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		glBindAttribLocation__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u24209(app__main_u30.program, ((NU32)1), "a_color");
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		glLinkProgram__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u2128(app__main_u30.program);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		glDeleteShader__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u20728(vertShader);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		glDeleteShader__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u20728(fragShader);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		echoBinSafe(TM__59aBxGWp6q9aemWfj0Y3wGlA_28, 1);
	}
LA4_: ;
	glUseProgram__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u14310(app__main_u30.program);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		if (!(app__main_u30.vertexBuffer == ((NU32)0))) goto LA15_;
		glGenBuffers__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u8304(((NI32)1), (&app__main_u30.vertexBuffer));
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
LA15_: ;
	glBindBuffer__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u914(((NU32)34962), app__main_u30.vertexBuffer);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	stride = ((NI32)24);
	glEnableVertexAttribArray__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u20888(((NU32)0));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	glVertexAttribPointer__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u11864(((NU32)0), ((NI32)3), ((NU32)5126), NIM_FALSE, stride, ((void*) (((NI)0))));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	glEnableVertexAttribArray__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u20888(((NU32)1));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	glVertexAttribPointer__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u11864(((NU32)1), ((NI32)3), ((NU32)5126), NIM_FALSE, stride, ((void*) (((NI)12))));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	vertices.len = 18; vertices.p = (tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content*) newSeqPayload(18, sizeof(NF32), NIM_ALIGNOF(NF32));
	vertices.p->data[0] = ((NF32)(((NF32) (app__main_u30.offsetX))) + (NF32)(0.0f));
	vertices.p->data[1] = ((NF32) (((NF)(((NF) (((NF32) (app__main_u30.offsetY))))) + (NF)(0.5))));
	vertices.p->data[2] = 0.0f;
	vertices.p->data[3] = 1.0f;
	vertices.p->data[4] = 0.0f;
	vertices.p->data[5] = 0.0f;
	vertices.p->data[6] = ((NF32)(((NF32) (app__main_u30.offsetX))) - (NF32)(0.5f));
	vertices.p->data[7] = ((NF32) (((NF)(((NF) (((NF32) (app__main_u30.offsetY))))) - (NF)(0.5))));
	vertices.p->data[8] = 0.0f;
	vertices.p->data[9] = 0.0f;
	vertices.p->data[10] = 1.0f;
	vertices.p->data[11] = 0.0f;
	vertices.p->data[12] = ((NF32)(((NF32) (app__main_u30.offsetX))) + (NF32)(0.5f));
	vertices.p->data[13] = ((NF32) (((NF)(((NF) (((NF32) (app__main_u30.offsetY))))) - (NF)(0.5))));
	vertices.p->data[14] = 0.0f;
	vertices.p->data[15] = 0.0f;
	vertices.p->data[16] = 0.0f;
	vertices.p->data[17] = 1.0f;
	T17_ = vertices.len;
	T18_ = (NI)0;
	T18_ = (NI)(T17_ * ((NI)4));
	glBufferData__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u10101(((NU32)34962), T18_, ((void*) ((&vertices.p->data[((NI)0)]))), ((NU32)35044));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	glDrawArrays__OOZOOZOOZOOZOOZOOZOOZOnimbleZpkgs50Zopengl4549O50O57455655ece57f51a57f5757d4955515150b5348565653e4953a52dcb4956c5349b53Zopengl_u13759(((NU32)4), ((NI32)0), ((NI32)3));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		eqdestroy___main_u738(vertices);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, pluseq___main_u473)(double* x_p0, double y_p1) {
	(*x_p0) = ((NF)((*x_p0)) + (NF)(y_p1));
}
static N_INLINE(void, minuseq___main_u477)(double* x_p0, double y_p1) {
	(*x_p0) = ((NF)((*x_p0)) - (NF)(y_p1));
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, onTouch__main_u19)(void** display_p0, int touch_p1, tyEnum_GLFMTouchPhase__ClxE9ajyzPj3mn2CrAmSDdw phase_p2, double x_p3, double y_p4) {
	NIM_BOOL result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	{
		if (!(phase_p2 == ((tyEnum_GLFMTouchPhase__ClxE9ajyzPj3mn2CrAmSDdw)0))) goto LA3_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
LA3_: ;
	{
		NimStringV2 colontmpD_;
		NimStringV2 colontmpD__2;
		int width;
		int height;
		tyArray__sMpvt1sOxOJ3LFGulnbeMQ T10_;
		if (!!((phase_p2 == ((tyEnum_GLFMTouchPhase__ClxE9ajyzPj3mn2CrAmSDdw)1)))) goto LA7_;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
		width = (int)0;
		height = (int)0;
		glfmGetDisplaySize(display_p0, ((int*) ((&width))), ((int*) ((&height))));
		pluseq___main_u473(((double*) ((&app__main_u30.offsetX))), ((NF)(((NF)(2.0) * (NF)(((NF)(x_p3) - (NF)(app__main_u30.lastTouchX))))) / (NF)(((NF) (width)))));
		minuseq___main_u477(((double*) ((&app__main_u30.offsetY))), ((NF)(((NF)(2.0) * (NF)(((NF)(y_p4) - (NF)(app__main_u30.lastTouchY))))) / (NF)(((NF) (height)))));
		T10_[0] = TM__59aBxGWp6q9aemWfj0Y3wGlA_32;
		colontmpD_ = dollar___main_u490(app__main_u30.offsetX);
		if (NIM_UNLIKELY(*nimErr_)) goto LA9_;
		T10_[1] = colontmpD_;
		T10_[2] = TM__59aBxGWp6q9aemWfj0Y3wGlA_34;
		colontmpD__2 = dollar___main_u490(app__main_u30.offsetY);
		if (NIM_UNLIKELY(*nimErr_)) goto LA9_;
		T10_[3] = colontmpD__2;
		echoBinSafe(T10_, 4);
		{
			LA9_:;
		}
		{
			if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
			if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA7_: ;
	app__main_u30.lastTouchX = x_p3;
	app__main_u30.lastTouchY = y_p4;
	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, onKey__main_u25)(void** display_p0, tyEnum_GLFMKey__GrBAa2tzG9ajXYl9bCEity1w keyCode_p1, tyEnum_GLFMKeyAction__YTIfOfrNucIeZ9bSR9bZFUNw action_p2, int modifiers_p3) {
	NIM_BOOL result;
	NIM_BOOL handled;
{	handled = NIM_FALSE;
	{
		if (!(action_p2 == ((tyEnum_GLFMKeyAction__YTIfOfrNucIeZ9bSR9bZFUNw)0))) goto LA3_;
		switch (keyCode_p1) {
		case ((tyEnum_GLFMKey__GrBAa2tzG9ajXYl9bCEity1w)37):
		{
			minuseq___main_u477(((double*) ((&app__main_u30.offsetX))), 0.1);
			handled = NIM_TRUE;
		}
		break;
		case ((tyEnum_GLFMKey__GrBAa2tzG9ajXYl9bCEity1w)39):
		{
			pluseq___main_u473(((double*) ((&app__main_u30.offsetX))), 0.1);
			handled = NIM_TRUE;
		}
		break;
		case ((tyEnum_GLFMKey__GrBAa2tzG9ajXYl9bCEity1w)38):
		{
			minuseq___main_u477(((double*) ((&app__main_u30.offsetY))), 0.1);
			handled = NIM_TRUE;
		}
		break;
		case ((tyEnum_GLFMKey__GrBAa2tzG9ajXYl9bCEity1w)40):
		{
			pluseq___main_u473(((double*) ((&app__main_u30.offsetY))), 0.1);
			handled = NIM_TRUE;
		}
		break;
		default:
		{
		}
		break;
		}
	}
LA3_: ;
	result = handled;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, glfmMain)(void** display_p0) {
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ s;
	NimStringV2 colontmpD_;
	tyArray__nHXaesL0DJZHyVS07ARPRA T2_;
	NI T3_;
	tyProc__d0tzLLq7AbEObpKtlZImpA T4_;
	tyProc__d0tzLLq7AbEObpKtlZImpA T5_;
	tyProc__OWoMzYmTKPUvWrQhzvWLBA T6_;
	tyProc__B38YaKbIJZkI8xoQ6zVwxQ T7_;
	tyProc__bQ863fx7S8H7f1ucLoHUQw T8_;
	tyProc__XLpcabov1HBFAn7gm9cb8hQ T9_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	s.len = 0; s.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	NimMain();
	echoBinSafe(TM__59aBxGWp6q9aemWfj0Y3wGlA_2, 1);
	s = newSeq__main_u130(((NI)100));
	T3_ = s.len;
	colontmpD_ = dollar___systemZdollars_u8(T3_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_[0] = colontmpD_;
	echoBinSafe(T2_, 1);
	echoBinSafe(TM__59aBxGWp6q9aemWfj0Y3wGlA_4, 1);
	glfmSetDisplayConfig(display_p0, ((tyEnum_GLFMRenderingAPI__X9cPQp6TMCe7CyGitWYnmFQ)0), ((tyEnum_GLFMColorFormat__B5oVFc9a9bleZEcxsprXxuGQ)0), ((tyEnum_GLFMDepthFormat__7cjWm8ekVbrcorhokDJT9aQ)0), ((tyEnum_GLFMStencilFormat__qQnIOhnCNoFb7KzllnQU8w)0), ((tyEnum_GLFMMultisample__LKoPnOwXYDp1HTCRyATojQ)0));
	glfmSetUserData(display_p0, ((void*) ((&app__main_u30))));
	nimZeroMem((void*)(&T4_), sizeof(tyProc__d0tzLLq7AbEObpKtlZImpA));
	T4_.ClP_0 = ((TM__59aBxGWp6q9aemWfj0Y3wGlA_6) (onSurfaceCreated__main_u13)); T4_.ClE_0 = NIM_NIL;
	glfmSetSurfaceCreatedFunc(display_p0, T4_);
	nimZeroMem((void*)(&T5_), sizeof(tyProc__d0tzLLq7AbEObpKtlZImpA));
	T5_.ClP_0 = ((TM__59aBxGWp6q9aemWfj0Y3wGlA_7) (onSurfaceCreated__main_u13)); T5_.ClE_0 = NIM_NIL;
	glfmSetSurfaceResizedFunc(display_p0, T5_);
	nimZeroMem((void*)(&T6_), sizeof(tyProc__OWoMzYmTKPUvWrQhzvWLBA));
	T6_.ClP_0 = ((TM__59aBxGWp6q9aemWfj0Y3wGlA_8) (onSurfaceDestroyed__main_u17)); T6_.ClE_0 = NIM_NIL;
	glfmSetSurfaceDestroyedFunc(display_p0, T6_);
	nimZeroMem((void*)(&T7_), sizeof(tyProc__B38YaKbIJZkI8xoQ6zVwxQ));
	T7_.ClP_0 = ((TM__59aBxGWp6q9aemWfj0Y3wGlA_30) (onFrame__main_u10)); T7_.ClE_0 = NIM_NIL;
	glfmSetMainLoopFunc(display_p0, T7_);
	nimZeroMem((void*)(&T8_), sizeof(tyProc__bQ863fx7S8H7f1ucLoHUQw));
	T8_.ClP_0 = ((TM__59aBxGWp6q9aemWfj0Y3wGlA_35) (onTouch__main_u19)); T8_.ClE_0 = NIM_NIL;
	glfmSetTouchFunc(display_p0, T8_);
	nimZeroMem((void*)(&T9_), sizeof(tyProc__XLpcabov1HBFAn7gm9cb8hQ));
	T9_.ClP_0 = ((TM__59aBxGWp6q9aemWfj0Y3wGlA_36) (onKey__main_u25)); T9_.ClE_0 = NIM_NIL;
	glfmSetKeyFunc(display_p0, T9_);
	{
		LA1_:;
	}
	{
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		eqdestroy___main_u141(s);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}

N_LIB_PRIVATE void PreMainInner(void) {
}

N_LIB_PRIVATE void PreMain(void) {
#if 0
	void (*volatile inner)(void);
	inner = PreMainInner;
	(*inner)();
#else
	PreMainInner();
#endif
}

N_LIB_PRIVATE N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
#if 0
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	(*inner)();
#else
	PreMain();
	NimMainInner();
#endif
}

N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
{
	NimStringV2 colontmpD_;
	tyArray__nHXaesL0DJZHyVS07ARPRA T2_;
	NI T3_;
NIM_BOOL* nimErr_;
nimErr_ = nimErrorFlag();
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	echoBinSafe(TM__59aBxGWp6q9aemWfj0Y3wGlA_37, 1);
	s__main_u902 = newSeq__main_u130(((NI)100));
	T3_ = s__main_u902.len;
	colontmpD_ = dollar___systemZdollars_u8(T3_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_[0] = colontmpD_;
	echoBinSafe(T2_, 1);
	echoBinSafe(TM__59aBxGWp6q9aemWfj0Y3wGlA_39, 1);
	{
		LA1_:;
	}
	{
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	BeforeRet_: ;
	nimTestErrorFlag();
}
}

